config/urls.py
from django.contrib import admin
from django.urls import path, include
# from myweb.views import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('myweb/', include('myweb.urls')),
    # path('', views.index, name='index'),
]

myweb/urls.py
from django.urls import path
from . import views

app_name = 'myweb'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:post_id>/', views.detail, name='detail'),
    path('comment/create/<int:post_id>/', views.comment_create, name="comment_create"),
]

myweb/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    subject = models.CharField(max_length=200)  # 게시글 제목
    content = models.TextField()                # 게시글 내용
    create_date = models.DateTimeField()        # 게시글 작성일

    def __str__(self):
        return self.subject

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)    # 연결된 게시글 삭제시 같이 삭제됨.
    content = models.TextField()                # 댓글 내용
    create_date = models.DateTimeField()        # 댓글 작성일

myweb/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.utils import timezone
from .models import Post
from .models import Comment

# Create your views here.

def index(request):
    post_list = Post.objects.order_by('-create_date')
    context = {'post_list :': post_list}
    return render(request, 'myweb/post_list.html',context)

def detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    context = {'post':post}
    return render(request, 'myweb/post_detail.html', context)

def comment_create(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    comment = Comment(post=post, content=request.POST.get('content'), create_date=timezone.now())
    comment.save()
    return redirect('myweb:detail', post_id=post.id)

templates/myweb/post_detail.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
<div class="container my-3">
    <!-- 게시글 -->
    <h2 class="border-bottom py-2">{{ post.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ post.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ post.create_date }}
                </div>
            </div>
        </div>
    </div>
    <!-- 댓글 -->
    <h5 class="border-bottom my-3 py-2">{{post.comment_set.count}}개의 댓글이 있습니다.</h5>
    {% for comment in post.comment_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ comment.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ comment.create_date }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- 댓글 등록 -->
    <form action="{% url 'myweb:comment_create' post.id %}" method="post" class="my-3">
        {% csrf_token %}
        <div class="mb-3">
            <label for="content" class="form-label">댓글내용</label>
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>

templates/myweb/post_list.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="table-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if post_list %}
        {% for post in post_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>
                <a href="{% url 'pybo:detail' post.id %}">{{ post.subject }}</a>
            </td>
            <td>{{ post.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">게시글이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
</div>